[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn followup_buddy.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
